<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddFamilyMemeber_Button</name>
   <tag></tag>
   <elementGuidId>a4855419-a895-4471-8e4e-30fb520ec17c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.z-ImageButton.z-TableTreeItemImageButtonColumnValue-Image.z-TableTreeItemImageButtonColumnValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@title='Add Family Link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8f6454b5-0e36-4779-9229-7e8e7430294a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>system/icons/plus.png</value>
      <webElementGuid>baaa5d5b-0c48-44b8-94c0-7c2976b4dbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> z-ImageButton z-TableTreeItemImageButtonColumnValue-Image z-TableTreeItemImageButtonColumnValue</value>
      <webElementGuid>09a820b6-d2b3-4f6f-b0f5-bd3cd3283866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Family Link</value>
      <webElementGuid>cef1c473-1c4d-4c37-8213-c819b57d272b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;z-WorkspaceHolder&quot;]/div[2]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[2]/div[@class=&quot;gwt-SplitLayoutPanel&quot;]/div[4]/div[@class=&quot;z-DataView z-DataView-Selected&quot;]/div[2]/div[1]/div[3]/div[@class=&quot;z-FlowVerticalPanel z-Workspace&quot;]/div[@class=&quot;zrl-FlexVertical&quot;]/div[@class=&quot;z-FlowVerticalPanel z-RoundedPanelFullWidth zrl-FlexUseAvailableVertical&quot;]/div[@class=&quot;cellTreeWidget&quot;]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;cellTreeItem cellTreeTopItem&quot;]/div[@class=&quot;cellTreeItem cellTreeItemImageValue cellTreeTopItemImageValue&quot;]/div[@class=&quot;cellTreeItemValue&quot;]/div[@class=&quot;z-TreeItem-PersonTypeLevel z-TableTreeRow z-TableTreeItemRowOdd&quot;]/div[@class=&quot;z-VertAlignMiddle z-TableTreeCell z-TableTreeImageButtonCellContainer&quot;]/img[@class=&quot;z-ImageButton z-TableTreeItemImageButtonColumnValue-Image z-TableTreeItemImageButtonColumnValue&quot;]</value>
      <webElementGuid>17ac1511-3e1a-4578-8c4e-f135b6c3275c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Add Family Link']</value>
      <webElementGuid>35949e85-4cf0-4d17-b649-f47ae441dc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/img</value>
      <webElementGuid>61ab39c4-3ff9-456b-b4e8-6355cd6b864b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'system/icons/plus.png' and @title = 'Add Family Link']</value>
      <webElementGuid>3782df6a-b471-44b9-a870-e7e5db29100b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
