<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mikchael Hany Mikael Shafiq Abdelmallek</name>
   <tag></tag>
   <elementGuidId>dc5c90cc-bf9d-4cde-9a89-22b24e0b2435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='default']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e27cb051-bcaf-4237-82d6-aa4269610019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>acfd0808-6be7-44b8-a462-9fb50bd0bf0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> z-CommandLabel</value>
      <webElementGuid>132cacaf-6377-48e1-b1a6-bd33ccdecd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mikchael Hany Mikael Shafiq Abdelmallek</value>
      <webElementGuid>2879df34-3cd3-4738-871f-0595f7739864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default&quot;)</value>
      <webElementGuid>c1cf8eb8-a63e-4535-99b2-bf6ed046aa74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='default']</value>
      <webElementGuid>b6403b8d-81c4-4728-8f28-d532a72c1356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T000182679'])[1]/following::div[4]</value>
      <webElementGuid>cea3810f-643a-4e9f-af52-587d4ed661eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phones'])[1]/following::div[20]</value>
      <webElementGuid>2b575cb2-efb2-4dbd-99c0-41ce3f647fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tawfiqmakram22@gmail.com'])[1]/preceding::div[2]</value>
      <webElementGuid>838d7161-370d-487e-acf3-f8f737d3daf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mikchael Hany Mikael Shafiq Abdelmallek']/parent::*</value>
      <webElementGuid>ae4e3d9c-8f81-4519-99ce-21107ff5fcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div</value>
      <webElementGuid>bc528f03-8832-48b5-a1f8-a62e5231404a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'default' and (text() = 'Mikchael Hany Mikael Shafiq Abdelmallek' or . = 'Mikchael Hany Mikael Shafiq Abdelmallek')]</value>
      <webElementGuid>39f31c90-235c-4544-af07-c17a4b370cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
