<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FamilyMember_Button</name>
   <tag></tag>
   <elementGuidId>d54b7109-99c7-4226-9be3-9b40de36790d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='default']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a808c0f8-2aec-45b1-badd-d9f6b3ed2f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>699933b4-60dd-4f29-a224-18388082affc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> z-CommandLabel</value>
      <webElementGuid>8787c6d0-1cb6-4dab-8a7a-be86d05ee5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>makram mikael</value>
      <webElementGuid>7e64d63b-1abc-4066-8d6f-846165d8dc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default&quot;)</value>
      <webElementGuid>6de0667f-418a-4dec-9c98-8fcdf6ed8d2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='default']</value>
      <webElementGuid>2b88c5e0-19ec-4f72-a32e-fa69f56c4cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phones'])[1]/following::div[20]</value>
      <webElementGuid>7eeb21f7-a0ac-4a32-936d-3e945b24da4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birth Date'])[1]/following::div[20]</value>
      <webElementGuid>836385e7-a268-4032-9e48-975a87d0a7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::div[15]</value>
      <webElementGuid>57456665-7bd5-46f7-b02b-0a651b8ec480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::div[15]</value>
      <webElementGuid>e4cc8924-b0bf-4b36-bb57-3fef83765b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='makram mikael']/parent::*</value>
      <webElementGuid>6c7f098c-e3c2-497d-b2b2-8533de33f355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div</value>
      <webElementGuid>8c896ca0-02bb-4ce0-96b6-af8e6e03c84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'default' and (text() = 'makram mikael' or . = 'makram mikael')]</value>
      <webElementGuid>fbc6ef91-d81f-4084-a350-88239e240cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
