<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudentDetails_Button</name>
   <tag></tag>
   <elementGuidId>03d98f1a-4863-4da3-887c-1a4afdb503e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.z-MenuItem-Action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e371d47-f227-4a99-8a27-21da2a0dc5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd21e4c4-d64c-4150-b382-2b30c873cfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-MenuItem-Action</value>
      <webElementGuid>edbfa6c3-7947-4b1a-89c1-c53f018bed5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Student Details</value>
      <webElementGuid>4e176609-de42-468f-b638-575e314d6848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;gwt-PopupPanel&quot;]/div[@class=&quot;popupContent&quot;]/table[1]/tbody[1]/tr[1]/td[1]/button[@class=&quot;z-MenuItem-Action&quot;]</value>
      <webElementGuid>1acdf1df-037a-4acf-ac23-ebccb5792bac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>33813d01-08e7-40bb-967f-9416d0abf9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tawfiqmakram22@gmail.com'])[1]/following::button[1]</value>
      <webElementGuid>533b5004-3d28-4738-ab8f-846202372dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mikchael Hany Mikael Shafiq Abdelmallek'])[1]/following::button[1]</value>
      <webElementGuid>08efe982-d8cb-40a9-a006-78f09b9bc0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Exemplary'])[1]/preceding::button[1]</value>
      <webElementGuid>5aaeca35-c62f-420f-ab02-f9e7cebc4b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>f856cdf9-43bd-4228-bd99-b524e87f7ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Student Details' or . = 'Student Details')]</value>
      <webElementGuid>55bd65a5-06ec-46d8-9f6e-f518c70f324b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
