<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exception_SubMenu</name>
   <tag></tag>
   <elementGuidId>b1b80ba4-7149-4ade-bcbf-b847b7350b70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Exceptions' or . = 'Exceptions')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0757c8d4-502f-49d9-837e-c7061ab072d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2eee3ac1-98ba-4bb2-9a03-88ff14fec94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-MenuItem-Action</value>
      <webElementGuid>04474cfd-1c68-4adb-93d0-5024d69235fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exceptions</value>
      <webElementGuid>80884f19-2743-4fb5-a04e-3f64abb41045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;gwt-PopupPanel&quot;]/div[@class=&quot;popupContent&quot;]/table[1]/tbody[1]/tr[3]/td[1]/button[@class=&quot;z-MenuItem-Action&quot;]</value>
      <webElementGuid>1ca996fb-7ba1-49b7-96ce-b9e60ee4c4bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Exceptions' or . = 'Exceptions')]</value>
      <webElementGuid>a8c91ac4-24b5-4214-b41c-669f15400323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
