<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload Attachment_File2</name>
   <tag></tag>
   <elementGuidId>de8ef646-f39a-4357-adb2-0cd5ad6a2096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > div.z-FlowVerticalPanel > div.z-FlowVerticalPanel.z-Margin-Top-10.z-AddMargin.z-MandatoryLabel > div.z-FlowVerticalPanel.z-MandatoryAttribute > div.z-FlowHorizontalPanel > form > div.fileUpload.GKIQDVXHOD > input[name=&quot;File&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='File'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f30d0e0-5203-4ff7-a75b-8ebbf218cb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a495272c-edbf-4ce5-84ce-29fb5f1eeda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-FileUpload upload</value>
      <webElementGuid>15512676-7f9e-41ba-9dcb-87ff5d93352a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>File</value>
      <webElementGuid>dbd35a3f-7aa8-4154-a361-ac77dd04c7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;z-DialogBox fadeIn&quot;]/div[1]/table[1]/tbody[1]/tr[@class=&quot;dialogMiddle&quot;]/td[@class=&quot;dialogMiddleCenter&quot;]/div[@class=&quot;dialogMiddleCenterInner dialogContent&quot;]/div[@class=&quot;z-DialogBoxContent&quot;]/div[1]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-ScrollPage&quot;]/div[@class=&quot;z-Scroll&quot;]/div[1]/div[@class=&quot;z-FlowVerticalPanel z-Panel&quot;]/div[2]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel z-Margin-Top-10 z-AddMargin z-MandatoryLabel&quot;]/div[@class=&quot;z-FlowVerticalPanel z-MandatoryAttribute&quot;]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/form[1]/div[@class=&quot;fileUpload GKIQDVXHOD&quot;]/input[@class=&quot;gwt-FileUpload upload&quot;]</value>
      <webElementGuid>2a31acef-17a0-4e91-97af-f3880b953346</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='File'])[2]</value>
      <webElementGuid>675536ca-f98b-4381-9cca-67abf5c97c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[4]/div/div/form/div/input</value>
      <webElementGuid>8bad6529-2100-4ea4-abc1-6f92b01ecca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'File']</value>
      <webElementGuid>6c0e6f51-8715-4004-8116-5b8f63967612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
